version: "3"

services:
  backend:
    container_name: backend
    env_file:
      - ./.env
    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    command:
      - /start-reload.sh
    expose:
      - "80:80"
    # ports:
    #   - "80:8882"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/
      - ./frontend/node_modules:/app/node_modules
    command:
      - npm
      - run
      - dev
      - --
      - --host
      - 0.0.0.0
      - --port
      - "8883"
    ports:
      - "8883:8883"
    depends_on:
      - backend

    environment:
      - NODE_ENV=development

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8884:8884"
    depends_on:
      - backend
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
      # - ./static:/usr/src/app/static

